# Site settings
title: Thibault Guillaumont's Website
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://thibaultguillaumont.github.io/" # the base hostname & protocol for your site
site_url: "https://thibaultguillaumont.github.io/"
author: Copyright &copy; 2019 - Start Bootstrap
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: false
 hard_wrap: false
 syntax_highlighter: rouge

sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
  - vendor


collections:
  projects:
    output: true
    permalink: /projects/:path/
